# -*- coding: utf-8 -*-
"""cardiomyopathy_restart_training_25June2025_v5ok.Aug21st.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CRjf4LLMTpfFVA0jxmTNphu3o8QoCAj
"""

!pip install -U transformers
!pip install -q huggingface_hub

# Cell 1: Git LFS installation and repository cloning
# Install git-lfs
!sudo apt-get update
!sudo apt-get install -y git-lfs
!git lfs install

# Clone the Geneformer repository
!git clone https://huggingface.co/ctheodoris/Geneformer

# Cell 2: Install the Geneformer Python package
!cd Geneformer && pip install .

# Optional: Verify installation by importing
import os
import sys
# Add the cloned repo's directory to sys.path if 'pip install .' doesn't make it available immediately
# (Sometimes Colab needs a restart, but this can help)
if '/content/Geneformer' not in sys.path:
    sys.path.insert(0, '/content/Geneformer')

from geneformer import Classifier, EmbExtractor
print("Geneformer imported successfully!")

!ls /content/Geneformer

from geneformer import EmbExtractor

# Create the directory
# !mkdir -p /content/Genecorpus-30M

# Clone with sparse checkout for only example_input_files
# !git clone --filter=blob:none --sparse https://huggingface.co/datasets/ctheodoris/Genecorpus-30M /content/Genecorpus-30M

# Configure sparse checkout to only include example_input_files
# !cd /content/Genecorpus-30M && git sparse-checkout set example_input_files

# Check what was downloaded
# !ls -la /content/Genecorpus-30M/
# !find /content/Genecorpus-30M -type f -name "*.dataset"

# Commented out IPython magic to ensure Python compatibility.
# Clone only the `example_input_files` folder
!git clone --filter=blob:none --no-checkout https://huggingface.co/datasets/ctheodoris/Genecorpus-30M
# %cd Genecorpus-30M
!git sparse-checkout init --cone
!git sparse-checkout set example_input_files
!git checkout main

!cd /content/
!pwd

from huggingface_hub import snapshot_download
import os

# Create directory
os.makedirs("/content/datasets", exist_ok=True)

# Download only the disease_classification directory
dataset_path = snapshot_download(
    repo_id="ctheodoris/Genecorpus-30M",
    repo_type="dataset",
    local_dir="/content/datasets",
    local_dir_use_symlinks=False,
    allow_patterns="example_input_files/cell_classification/disease_classification/*"
)

print(f"Downloaded to: {dataset_path}")
!ls -la /content/datasets/example_input_files/cell_classification/disease_classification/

!pwd
!ls -la ./Geneformer/fine_tuned_models/

# Commented out IPython magic to ensure Python compatibility.
!pwd
!echo "-------"
# %cd /content/
!pwd
!echo "-------"
!ls -1
!echo "-------"
!echo "Genecorpus-30M"
!ls -1 /content/Genecorpus-30M
!echo "-------"
!ls -1
!echo "-------"
!echo "Geneformer"
!ls -1 /content/Geneformer
!echo "-------"
!echo "datasets"
!ls -1 /content/datasets
!echo "-------"

!echo "fined tune model"
!ls -la /content/Geneformer/fine_tuned_models/Geneformer-V1-10M_CellClassifier_cardiomyopathies_220224/
!echo "----------------------"
!echo "disease classification"
!ls -1 Genecorpus-30M/example_input_files/cell_classification/disease_classification
!ls -1 Genecorpus-30M/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset



!echo "gene dictionaries"
!ls -la /content/Geneformer/geneformer/gene_dictionaries_30m

import os

# Verify the file exists
token_path = "/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl"
print(f"Token dictionary exists: {os.path.exists(token_path)}")
print(f"Full path: {os.path.abspath(token_path)}")

# List all token files to see what's available
!ls -la /content/Geneformer/geneformer/*token*



# What is <cls>?

# The <cls> token is prepended to the input sequence.
# It stands for "classification", and is meant to capture a summary representation of the entire input.
# After passing the sequence through the Transformer, the final hidden state corresponding to the <cls> token is typically used as the aggregate representation for classification tasks.

# GPT4 info : it might not be accurate !

# Geneformer V1 and V2 both utilize a special <cls> token in their transformer models — but with some differences in implementation and usage context.

# 🔹 Geneformer V1
# Based on BERT architecture, which uses the <cls> token at the start of the input.
# The <cls> token embedding is used for tasks like cell classification, gene embedding extraction, and regression.
# When extracting embeddings in cell classification mode, the output corresponding to <cls> (usually the first token) is used as the representation of the cell.

#🔹 Geneformer V2
# Also maintains a classification token, although implementation and tokenization may differ slightly.
# It uses an updated model structure and dictionary (shared_gene_dict.json) which includes the <cls> token.
# The V2 architecture is more modular, but still retains the <cls> token for tasks requiring whole-sequence representation.

import datetime
import os
from geneformer import EmbExtractor

!echo ""
!echo "model : Geneformer-V1-10M"
!ls -1 /content/Geneformer/Geneformer-V1-10M
!echo ""
!echo "model : Geneformer-V2-104M"
!ls -1 /content/Geneformer/Geneformer-V2-104M
!echo ""
!echo "fined tune model"
!ls -la /content/Geneformer/fine_tuned_models/Geneformer-V1-10M_CellClassifier_cardiomyopathies_220224/

# Use V1 Model with CLS token (if you need CLS embeddings)
# If you want to extract <cls> embeddings, switch to a V1 model and provide a token dictionary that includes <cls>.
# About V2 model (model_version="V2") : the input data might be tokenized using a V1 tokenizer, which prepends a <cls> token.
# V2 Geneformer does not use <cls> tokens. So when emb_mode="cls" is attempted, it crashes because the first token is not <cls>.

# Check for available token dictionaries
!find /content -name "*token_dictionary*" -type f
!find /content -name "*.pkl" -type f | grep -i token

!ls -1 /content/Geneformer/geneformer/gene_dictionaries_30m/

# Model versions

model_version1="V1"
# model_version2="V2"

# Define paths

token_dictionary_file = "/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl"  # or your V1 or V2 token dict
token_dict_path = token_dictionary_file

model_directory = "/content/Geneformer/Geneformer-V1-10M"      # pretrained or fine-tuned model folder
# model_directory = "/content/Geneformer/Geneformer-V2-104M"   # pretrained or fine-tuned model folder
# model_directory = "/content/Geneformer/fine_tuned_models/Geneformer-V1-10M_CellClassifier_cardiomyopathies_220224/"

input_data_file = "/content/Genecorpus-30M/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset"

# Verify the paths

if os.path.exists(token_dictionary_file):
    print(f"✅ File exists: {token_dictionary_file}")
else:
    print(f"❌ File does NOT exist: {token_dictionary_file}")

if os.path.exists(model_directory):
    print(f"✅ File exists: {model_directory}")
else:
    print(f"❌ File does NOT exist: {model_directory}")


if os.path.exists(input_data_file):
    print(f"✅ File exists: {input_data_file}")
else:
    print(f"❌ File does NOT exist: {input_data_file}")

!ls -1 /content/Geneformer/geneformer/gene_dictionaries_30m/

# For V1 models:

# They do use the <cls> token — it is automatically prepended to the input.
# You must ensure that emb_mode="cell" is used when extracting cell embeddings.
# In your case, you don’t need to set emb_mode manually if you are using the CellClassifier model with model_version="V1", because that is the default behavior.

# However:
# If you manually set emb_mode="cls" or use code intended for V2 (which may handle embedding modes differently), it can trigger an assertion or lead to unexpected behavior.

!echo "verify the input files and output directory"

# WARNING:geneformer.emb_extractor:model_version selected as V1 so changing emb_mode from 'cls' to 'cell' as V1 models do not have a <cls> token.

from geneformer import EmbExtractor

# input_data_file
input_data_file = "/content/Genecorpus-30M/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset"

token_dictionary_file = "/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl"  # or your V1 or V2 token dict
# token_dictionary_file = "/content/Geneformer/geneformer/gene_dictionaries_30m/shared_gene_dict.json"
token_dict_path = token_dictionary_file

# model choices :
# model_directory = "/content/Geneformer/Geneformer-V1-10M"      # pretrained or fine-tuned model folder
# model_directory = "/content/Geneformer/Geneformer-V2-104M"   # pretrained or fine-tuned model folder
model_directory = "/content/Geneformer/fine_tuned_models/Geneformer-V1-10M_CellClassifier_cardiomyopathies_220224/"

import os
import warnings
import numpy as np
from collections import Counter
from datasets import load_from_disk

# Load the dataset
print(f"\n�� Loading dataset...")
try:
    dataset = load_from_disk(input_data_file)
    print(f"✅ Dataset loaded successfully!")
except Exception as e:
    print(f"❌ Failed to load dataset: {e}")
    exit()

# =============================================================================
# BASIC INFORMATION
# =============================================================================

print(f"\n📊 BASIC DATASET INFORMATION:")
print(f"   Total cells: {len(dataset):,}")
print(f"   Dataset type: {type(dataset)}")
print(f"   Number of columns: {len(dataset.column_names)}")

# =============================================================================
# COLUMN STRUCTURE
# =============================================================================

print(f"\n📋 COLUMN STRUCTURE:")
print(f"   Available columns: {dataset.column_names}")

print(f"\n�� FEATURE SCHEMA:")
for col_name in dataset.column_names:
    col_type = dataset.features[col_name]
    print(f"   {col_name}: {col_type}")


# Check number of rows and columns
print(dataset.num_rows)
print(dataset.column_names)

# View a sample row
print(dataset[0])
print(dataset[1])
print(dataset[2])

# Data composition :

import pandas as pd

# Convert to DataFrame (if small enough)
df = dataset.to_pandas()

# Unique individuals
print("🧍 Unique individuals:", df['individual'].nunique())
print(df['individual'].value_counts(), end="\n\n")

# Unique cell types
print("🔬 Unique cell types:", df['cell_type'].nunique())
print(df['cell_type'].value_counts(), end="\n\n")

# Unique diseases
print("🩺 Disease types:", df['disease'].nunique())
print(df['disease'].value_counts(), end="\n\n")

# Age summary
print("🎂 Age summary:")
print(df['age'].describe(), end="\n\n")

# Assuming `dataset` is already loaded with Hugging Face `datasets`
# and has the schema you shared

# Convert to pandas for easy manipulation
df = dataset.to_pandas()

# Number of unique individuals
n_individuals = df['individual'].nunique()

# Number of unique diseases
n_diseases = df['disease'].nunique()

# Print the results
print(f"🧍 Number of unique individuals: {n_individuals}")
print(f"🩺 Number of unique diseases: {n_diseases}")

print("🩺 Disease types:")
print(df['disease'].value_counts())

"""**DOWNSAMPLE to 10 000 cells**


"""

# -*- coding: utf-8 -*-
"""
Downsample Cardiomyopathy Dataset to 10,000 cells
Keep cardiomyocytes and stratify by disease states (NF, HCM, DCM)
"""

import os
import warnings
import numpy as np
import pandas as pd
from collections import Counter
from datasets import load_from_disk, Dataset
from sklearn.model_selection import train_test_split

# Suppress warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Dataset path
input_data_file = "/content/Genecorpus-30M/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset"

print(" Downsampling Cardiomyopathy Dataset")
print("=" * 50)

# Load the dataset
print(f" Loading dataset...")
dataset = load_from_disk(input_data_file)
print(f"✅ Original dataset: {len(dataset):,} cells")

# =============================================================================
# ANALYZE ORIGINAL DATA
# =============================================================================

print(f"\n📊 ORIGINAL DATA ANALYSIS:")

# Check disease distribution
disease_counts = Counter(dataset["disease"])
print(f"   Disease distribution:")
for disease, count in disease_counts.items():
    percentage = (count / len(dataset)) * 100
    print(f"     {disease}: {count:,} cells ({percentage:.1f}%)")

# Check cell types if available
if "cell_type" in dataset.column_names:
    celltype_counts = Counter(dataset["cell_type"])
    print(f"\n   Cell type distribution:")
    for celltype, count in celltype_counts.items():
        percentage = (count / len(dataset)) * 100
        print(f"     {celltype}: {count:,} cells ({percentage:.1f}%)")

    # Check cardiomyocytes specifically
    cardio_cells = [celltype for celltype in celltype_counts.keys()
                   if 'cardiomyocyte' in celltype.lower() or 'cardio' in celltype.lower()]
    if cardio_cells:
        print(f"\n   Cardiomyocyte cell types found: {cardio_cells}")
        total_cardio = sum(celltype_counts[ct] for ct in cardio_cells)
        print(f"   Total cardiomyocytes: {total_cardio:,} cells")
else:
    print(f"   No 'cell_type' column found - assuming all cells are cardiomyocytes")

# =============================================================================
# DOWNSAMPLE STRATEGY
# =============================================================================

target_size = 10000
print(f"\n DOWNSAMPLE STRATEGY:")
print(f"   Target size: {target_size:,} cells")
print(f"   Stratify by: disease states (NF, HCM, DCM)")

# Calculate target per disease state (proportional to original)
total_original = len(dataset)
target_per_disease = {}

for disease, count in disease_counts.items():
    proportion = count / total_original
    target_count = int(target_size * proportion)
    target_per_disease[disease] = target_count

print(f"\n   Target distribution:")
for disease, target_count in target_per_disease.items():
    print(f"     {disease}: {target_count:,} cells")

# =============================================================================
# PERFORM DOWNSAMPLING
# =============================================================================

print(f"\n✂️ PERFORMING DOWNSAMPLING...")

downsampled_data = []

for disease, target_count in target_per_disease.items():
    # Get all cells for this disease
    disease_indices = [i for i, d in enumerate(dataset["disease"]) if d == disease]

    if len(disease_indices) >= target_count:
        # Randomly sample without replacement
        selected_indices = np.random.choice(disease_indices, size=target_count, replace=False)
    else:
        # If not enough cells, take all available
        selected_indices = disease_indices
        print(f"   ⚠️  Warning: Only {len(disease_indices):,} {disease} cells available, using all")

    # Convert numpy int64 to regular int for dataset indexing
    selected_indices = [int(idx) for idx in selected_indices]

    # Add selected cells to downsampled data
    for idx in selected_indices:
        downsampled_data.append(dataset[idx])

    print(f"   ✅ {disease}: {len(selected_indices):,} cells selected")

# =============================================================================
# CREATE DOWNSAMPLED DATASET
# =============================================================================

print(f"\n CREATING DOWNSAMPLED DATASET...")

# Convert to HuggingFace Dataset
downsampled_dataset = Dataset.from_list(downsampled_data)
print(f"✅ Downsampled dataset created: {len(downsampled_dataset):,} cells")

# =============================================================================
# VERIFY DOWNSAMPLED DATA
# =============================================================================

print(f"\n🔍 VERIFYING DOWNSAMPLED DATA:")

# Check disease distribution
downsampled_disease_counts = Counter(downsampled_dataset["disease"])
print(f"   Disease distribution:")
for disease, count in downsampled_disease_counts.items():
    percentage = (count / len(downsampled_dataset)) * 100
    print(f"     {disease}: {count:,} cells ({percentage:.1f}%)")

# Check cell types if available
if "cell_type" in downsampled_dataset.column_names:
    downsampled_celltype_counts = Counter(downsampled_dataset["cell_type"])
    print(f"\n   Cell type distribution:")
    for celltype, count in downsampled_celltype_counts.items():
        percentage = (count / len(downsampled_dataset)) * 100
        print(f"     {celltype}: {count:,} cells ({percentage:.1f}%)")

# =============================================================================
# SAVE DOWNSAMPLED DATASET
# =============================================================================

print(f"\n SAVING DOWNSAMPLED DATASET...")

output_path = "/content/cardiomyopathy_10k_downsampled.dataset"
downsampled_dataset.save_to_disk(output_path)
print(f"✅ Downsampled dataset saved to: {output_path}")

# =============================================================================
# SUMMARY
# =============================================================================

print(f"\n DOWNSAMPLE SUMMARY:")
print("=" * 40)
print(f"📊 Original dataset: {len(dataset):,} cells")
print(f"📊 Downsampled dataset: {len(downsampled_dataset):,} cells")
print(f"📊 Reduction: {((len(dataset) - len(downsampled_dataset)) / len(dataset) * 100):.1f}%")

print(f"\n🎯 Stratification maintained:")
for disease in disease_counts.keys():
    original_pct = (disease_counts[disease] / len(dataset)) * 100
    downsampled_pct = (downsampled_disease_counts[disease] / len(downsampled_dataset)) * 100
    print(f"   {disease}: {original_pct:.1f}% → {downsampled_pct:.1f}%")

print(f"\n✅ Downsampling completed successfully!")
print(f"📁 Output file: {output_path}")
print(f" Ready for training with reduced dataset size")

"""DOWNSAMPLE to 10 000 cells"""

"""
Cardiomyopathy Geneformer Training Script
Complete training pipeline for cardiomyopathy disease classification
Adapted from pancreas script structure
"""

import os
import warnings
import datetime
import numpy as np
import pandas as pd
import torch
import gc
from collections import Counter
from datasets import load_from_disk, Dataset
from geneformer import Classifier

# Suppress warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# =============================================================================
# CONFIGURATION
# =============================================================================

CONFIG = {
    # Dataset paths

    # "input_data_file": "/content/Genecorpus-30M/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset",
    "input_data_file":  "/content/cardiomyopathy_10k_downsampled.dataset",

    # Model paths
    "model_path": "/content/Geneformer/fine_tuned_models/Geneformer-V1-10M_CellClassifier_cardiomyopathies_220224/",
    "token_dictionary_file": "/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl",

    # Training parameters
    "num_train_epochs": 0.9,
    "learning_rate": 0.000804,
    "lr_scheduler_type": "polynomial",
    "warmup_steps": 1812,
    "weight_decay": 0.258828,
    "per_device_train_batch_size": 12,
    "seed": 73,
    "gradient_checkpointing": False,
    "fp16": False,

    # Model configuration
    "model_version": "V1",
    "freeze_layers": 2,
    "num_crossval_splits": 1,
    "forward_batch_size": 200,
    "nproc": 16,

    # Data splitting
    "train_ratio": 0.7,
    "eval_ratio": 0.15,
    "test_ratio": 0.15,
    "random_state": 73,

    # Output
    "output_prefix": "cardiomyopathy_classifier"
}

# =============================================================================
# SETUP AND VERIFICATION
# =============================================================================

print("🚀 Starting Cardiomyopathy Geneformer Training Pipeline")
print("=" * 60)

# Create timestamped output directory
current_date = datetime.datetime.now()
datestamp = f"{str(current_date.year)[-2:]}{current_date.month:02d}{current_date.day:02d}{current_date.hour:02d}{current_date.minute:02d}{current_date.second:02d}"
datestamp_min = f"{str(current_date.year)[-2:]}{current_date.month:02d}{current_date.day:02d}"

output_dir = f"/content/cardiomyopathy_output/{datestamp}"
os.makedirs(output_dir, exist_ok=True)

print(f"📁 Output directory: {output_dir}")
print(f"📅 Timestamp: {datestamp}")

# Verify all required files exist
print(f"\n🔍 Verifying files...")
required_files = [
    ("Input dataset", CONFIG["input_data_file"]),
    ("Model directory", CONFIG["model_path"]),
    ("Token dictionary", CONFIG["token_dictionary_file"])
]

for name, path in required_files:
    if os.path.exists(path):
        print(f"✅ {name}: {path}")
    else:
        print(f"❌ {name}: {path}")
        print(f"   File not found - please check the path")
        exit()

import os
import warnings
import datetime
import numpy as np
import pandas as pd
import torch
import gc
from collections import Counter
from datasets import load_from_disk, Dataset
from geneformer import Classifier

# =============================================================================
# LOAD AND PREPARE DATASET
# =============================================================================

print(f"\n📋 Loading dataset...")

try:
    dataset = load_from_disk(CONFIG["input_data_file"])
    print(f"✅ Dataset loaded successfully")
    print(f"   Size: {len(dataset)} cells")
    print(f"   Columns: {list(dataset.features.keys())}")

    # Check for required columns
    required_columns = ["input_ids", "disease"]
    missing_columns = [col for col in required_columns if col not in dataset.column_names]

    if missing_columns:
        print(f"❌ Missing required columns: {missing_columns}")
        print(f"   Available columns: {dataset.column_names}")
        exit()

    # Display disease distribution
    disease_counts = Counter(dataset["disease"])
    print(f"\n📊 Disease distribution:")
    for disease, count in disease_counts.items():
        print(f"   {disease}: {count} cells")

except Exception as e:
    print(f"❌ Failed to load dataset: {e}")
    exit()

# ==============================

# =============================================================================
# DATA SPLITTING
# =============================================================================

print(f"\n✂️ Creating data splits...")

def create_simple_splits(dataset, train_ratio=0.7, eval_ratio=0.15, test_ratio=0.15, random_state=42):
    """Create simple train/eval/test splits"""
    n_total = len(dataset)
    n_train = int(n_total * train_ratio)
    n_eval = int(n_total * eval_ratio)
    n_test = n_total - n_train - n_eval

    # Shuffle and split
    dataset_shuffled = dataset.shuffle(seed=random_state)

    # Assign split labels
    split_labels = ["train"] * n_train + ["eval"] * n_eval + ["test"] * n_test
    dataset_with_splits = dataset_shuffled.map(
        lambda example, idx: {"split": split_labels[idx]},
        with_indices=True
    )

    # Verify splits
    split_counts = Counter(dataset_with_splits["split"])
    print(f"   Train: {split_counts['train']} cells")
    print(f"   Eval: {split_counts['eval']} cells")
    print(f"   Test: {split_counts['test']} cells")

    return dataset_with_splits

# Create splits
dataset_with_splits = create_simple_splits(
    dataset,
    train_ratio=CONFIG["train_ratio"],
    eval_ratio=CONFIG["eval_ratio"],
    test_ratio=CONFIG["test_ratio"],
    random_state=CONFIG["random_state"]
)

# Save dataset with splits
split_dataset_path = f"{output_dir}/{CONFIG['output_prefix']}_with_splits.dataset"
dataset_with_splits.save_to_disk(split_dataset_path)
print(f"✅ Dataset with splits saved to: {split_dataset_path}")

# =============================================================================
# CONFIGURE TRAINING
# =============================================================================

print(f"\n⚙️ Configuring training...")

# Training arguments
training_args = {
    "num_train_epochs": CONFIG["num_train_epochs"],
    "learning_rate": CONFIG["learning_rate"],
    "lr_scheduler_type": CONFIG["lr_scheduler_type"],
    "warmup_steps": CONFIG["warmup_steps"],
    "weight_decay": CONFIG["weight_decay"],
    "per_device_train_batch_size": CONFIG["per_device_train_batch_size"],
    "seed": CONFIG["seed"],
    "gradient_checkpointing": CONFIG["gradient_checkpointing"],
    "fp16": CONFIG["fp16"],
}

print(f"📊 Training configuration:")
for key, value in training_args.items():
    print(f"   {key}: {value}")

# Initialize classifier
print(f"\n🔧 Initializing classifier...")
cc = Classifier(
    classifier="cell",
    cell_state_dict={"state_key": "disease", "states": "all"},
    filter_data=None,  # Use all disease states
    training_args=training_args,
    max_ncells=None,
    freeze_layers=CONFIG["freeze_layers"],
    num_crossval_splits=CONFIG["num_crossval_splits"],
    forward_batch_size=CONFIG["forward_batch_size"],
    model_version=CONFIG["model_version"],
    nproc=CONFIG["nproc"]
)

print("✅ Classifier initialized")

# Split dictionaries
train_test_split_dict = {
    "attr_key": "split",
    "train": ["train", "eval"],
    "test": ["test"]
}

train_eval_split_dict = {
    "attr_key": "split",
    "train": ["train"],
    "eval": ["eval"]
}

# =============================================================================
# PREPARE DATA
# =============================================================================

print(f"\n📋 Preparing data...")

try:
    cc.prepare_data(
        input_data_file=split_dataset_path,
        output_directory=output_dir,
        output_prefix=CONFIG["output_prefix"],
        split_id_dict=train_test_split_dict
    )
    print("✅ Data prepared")
except Exception as e:
    print(f"❌ Data preparation failed: {e}")
    exit()

# =============================================================================
# TRAIN MODEL
# =============================================================================

print(f"\n🚀 Training model...")

prepared_dataset_file = f"{output_dir}/{CONFIG['output_prefix']}_labeled_train.dataset"
id_class_dict_file = f"{output_dir}/{CONFIG['output_prefix']}_id_class_dict.pkl"

# Check if files exist
print(f"🔍 Checking files:")
print(f"  - Prepared dataset: {os.path.exists(prepared_dataset_file)}")
print(f"  - ID class dict: {os.path.exists(id_class_dict_file)}")
print(f"  - Model path: {os.path.exists(CONFIG['model_path'])}")

try:
    training_metrics = cc.validate(
        model_directory=CONFIG["model_path"],
        prepared_input_data_file=prepared_dataset_file,
        id_class_dict_file=id_class_dict_file,
        output_directory=output_dir,
        output_prefix=CONFIG["output_prefix"],
        split_id_dict=train_eval_split_dict
    )
    print("✅ Training completed!")

    # Safely display training metrics
    accuracy = training_metrics.get('accuracy', 'N/A')
    macro_f1 = training_metrics.get('macro_f1', 'N/A')

    if isinstance(accuracy, (int, float)):
        print(f"📊 Training accuracy: {accuracy:.4f}")
    else:
        print(f"📊 Training accuracy: {accuracy}")

    if isinstance(macro_f1, (int, float)):
        print(f"📊 Training F1: {macro_f1:.4f}")
    else:
        print(f"📊 Training F1: {macro_f1}")

except Exception as e:
    print(f"❌ Training failed: {e}")
    print(f"🔍 Error type: {type(e).__name__}")
    print(f"🔍 Error details: {str(e)}")

    # Check if it's a formatting error
    if "Unknown format code 'f'" in str(e):
        print("💡 This appears to be a formatting error in the Geneformer library.")
        print("💡 The training might have completed successfully despite this error.")
        print("💡 Let's try to continue with evaluation...")

        # Try to find the model anyway
        model_dirs = [d for d in os.listdir(output_dir) if "geneformer_cellClassifier" in d and CONFIG["output_prefix"] in d]
        if model_dirs:
            print("✅ Found trained model despite error - continuing...")
            # Don't exit, continue to evaluation
        else:
            print("❌ No trained model found - exiting")
            exit()
    else:
        exit()

# =============================================================================
# EVALUATE MODEL
# =============================================================================

print(f"\n🧪 Evaluating model...")

# Find trained model
model_dirs = [d for d in os.listdir(output_dir) if "geneformer_cellClassifier" in d and CONFIG["output_prefix"] in d]
if model_dirs:
    trained_model_dir = os.path.join(output_dir, model_dirs[0], "ksplit1")
    print(f"✅ Found model: {trained_model_dir}")

    # Check if the model directory actually exists
    if not os.path.exists(trained_model_dir):
        print(f"❌ Model directory does not exist: {trained_model_dir}")
        exit()
else:
    print("❌ Model not found")
    print("🔍 Checking output directory contents:")
    for item in os.listdir(output_dir):
        print(f"  - {item}")
    exit()

# Create evaluation classifier
eval_cc = Classifier(
    classifier="cell",
    cell_state_dict={"state_key": "disease", "states": "all"},
    forward_batch_size=CONFIG["forward_batch_size"],
    nproc=CONFIG["nproc"]
)

# Test files
test_data_file = f"{output_dir}/{CONFIG['output_prefix']}_labeled_test.dataset"

try:
    all_metrics_test = eval_cc.evaluate_saved_model(
        model_directory=trained_model_dir,
        id_class_dict_file=id_class_dict_file,
        test_data_file=test_data_file,
        output_directory=output_dir,
        output_prefix=f"{CONFIG['output_prefix']}_test"
    )
    print("✅ Evaluation completed!")

    # Show results
    print(f"\n📊 TEST RESULTS:")
    for key, value in all_metrics_test.items():
        if isinstance(value, (int, float)):
            print(f"  {key}: {value:.4f}")
        else:
            print(f"  {key}: {value}")

except Exception as e:
    print(f"❌ Evaluation failed: {e}")
    all_metrics_test = None

# =============================================================================
# CREATE PLOTS
# =============================================================================

if all_metrics_test:
    print(f"\n📊 Creating plots...")

    import matplotlib.pyplot as plt
    import seaborn as sns

    # Get unique disease states
    unique_diseases = list(disease_counts.keys())

    # Basic Geneformer plots
    try:
        eval_cc.plot_conf_mat(
            conf_mat_dict={"Geneformer": all_metrics_test["conf_matrix"]},
            output_directory=output_dir,
            output_prefix=CONFIG["output_prefix"],
            custom_class_order=unique_diseases,
        )
        print("✅ Confusion matrix saved")
    except Exception as e:
        print(f"❌ Confusion matrix failed: {e}")

    try:
        # Check what prediction files exist
        pred_files = [f for f in os.listdir(output_dir) if "pred_dict.pkl" in f]
        print(f"🔍 Available prediction files: {pred_files}")

        # Use the correct prediction file (with _test suffix from evaluation)
        predictions_file = f"{output_dir}/{CONFIG['output_prefix']}_test_pred_dict.pkl"

        if not os.path.exists(predictions_file):
            print(f"❌ Prediction file not found: {predictions_file}")
            print("🔍 Checking for alternative prediction files...")
            if pred_files:
                predictions_file = f"{output_dir}/{pred_files[0]}"
                print(f"💡 Using alternative file: {predictions_file}")
            else:
                print("❌ No prediction files found - skipping predictions plot")
                raise FileNotFoundError("No prediction files found")

        eval_cc.plot_predictions(
            predictions_file=predictions_file,
            id_class_dict_file=f"{output_dir}/{CONFIG['output_prefix']}_id_class_dict.pkl",
            title="Cardiomyopathy Disease States",
            output_directory=output_dir,
            output_prefix=CONFIG["output_prefix"],
            custom_class_order=unique_diseases,
        )
        print("✅ Predictions plot saved")
    except Exception as e:
        print(f"❌ Predictions plot failed: {e}")

# =============================================================================
# SAVE SUMMARY
# =============================================================================

print(f"\n📝 Saving summary...")

summary_file = f"{output_dir}/{CONFIG['output_prefix']}_simple_summary.txt"
with open(summary_file, 'w') as f:
    f.write("Cardiomyopathy Geneformer Training Summary\n")
    f.write("=" * 50 + "\n\n")

    f.write(f"Date: {current_date.strftime('%Y-%m-%d %H:%M:%S')}\n")
    f.write(f"Output directory: {output_dir}\n\n")

    f.write("Dataset Information:\n")
    f.write(f"  Total cells: {len(dataset)}\n")
    f.write("  Disease distribution:\n")
    for disease, count in disease_counts.items():
        f.write(f"    {disease}: {count}\n")
    f.write("\n")

    f.write("Training Configuration:\n")
    for key, value in training_args.items():
        f.write(f"  {key}: {value}\n")
    f.write("\n")

    if all_metrics_test:
        f.write("Test Results:\n")
        for key, value in all_metrics_test.items():
            if isinstance(value, (int, float)):
                f.write(f"  {key}: {value:.4f}\n")
            else:
                f.write(f"  {key}: {value}\n")

print(f"✅ Summary saved to: {summary_file}")

# =============================================================================
# FINAL SUMMARY
# =============================================================================

print(f"\n🎉 Training pipeline completed!")
print("=" * 60)

print(f"📁 Output directory: {output_dir}")
print(f"📊 Dataset: {len(dataset)} cells, {len(disease_counts)} disease states")
print(f"🔧 Model: {CONFIG['model_version']} fine-tuned for cardiomyopathy")

if all_metrics_test:
    print(f"📈 Test accuracy: {all_metrics_test.get('acc', 'N/A')}")
    print(f"📈 Test F1: {all_metrics_test.get('macro_f1', 'N/A')}")

print(f"\n📋 Generated files:")
print("  📊 Plots:")
print("    - Confusion matrix")
print("    - Predictions plot")
print("  📁 Data:")
print("    - Prepared dataset")
print("    - ID class dictionary")
print("    - Prediction files")
print("  📝 Summary:")
print("    - Training summary")
print("  🧠 Model:")
print("    - Trained model files")

print(f"\n✅ All done! Check the output directory for results.")

from google.colab import drive
drive.mount('/content/drive')

!ls -1 "/content/drive/My Drive/geneformer_test4_cardiomyopathy"

!ls -1 /content/cardiomyopathy_output/250821194621

# To continue with the insilico perturbation

!cp -r /content/cardiomyopathy_output/250821194621 "/content/drive/My Drive/geneformer_test4_cardiomyopathy"

!ls -1 "/content/drive/My Drive/geneformer_test4_cardiomyopathy"

!ls -1 "/content/drive/My Drive/geneformer_test4_cardiomyopathy/250821194621"