# -*- coding: utf-8 -*-
"""Geneformer_Anndata_Loom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSbJDh5-5d6AaLw_hEd1KoBcIhWAeRtm

**Geneformer, Anndata, Loom**
"""

!git lfs install
!git clone https://huggingface.co/ctheodoris/Geneformer
!cd Geneformer # Note: 'cd' in a notebook cell only changes the directory for that cell
!pip install .

# inspiration from : https://wang-lab.hkust.edu.hk/others/Tutorials/geneformer/seuToAnn.html
# !pip install gdrive

!pip install scanpy
!pip install loompy

# Install R if not already available
!apt-get update
!apt-get install -y r-base r-base-dev

!Rscript -e "install.packages(c('Seurat', 'devtools', 'remotes'), repos='https://cran.rstudio.com/')"

!Rscript -e "devtools::install_github('mojaveazure/seurat-disk')"
!Rscript -e "remotes::install_github('mojaveazure/seurat-disk')"

!Rscript -e "devtools::install_github('satijalab/seurat-data')"
!Rscript -e "install.packages('SeuratData', repos='https://cran.rstudio.com/')"

# Verify installation
!Rscript -e "library(Seurat); library(SeuratDisk); library(SeuratData); print('✅ Packages installed successfully!')"

import scanpy as sc
import pandas as pd

# Download the classic PBMC3k dataset
adata = sc.datasets.pbmc3k_processed()
print(adata)

# This gives you a pre-processed dataset with:
# - 2,638 cells × 1,838 genes
# - UMAP, PCA, and clustering already computed
# - Cell type annotations

# Basic exploration
print("Cell types:")
print(adata.obs['louvain'].value_counts())

# Quick UMAP plot
sc.pl.umap(adata, color='louvain', legend_loc='on data')

# Commented out IPython magic to ensure Python compatibility.
# Install R essentials and rpy2 interface

!apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
!pip install -q rpy2==3.5.11

# Load R magic
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(Seurat)
# library(SeuratData)
# library(SeuratDisk)
# 
# # Load dataset
# SeuratData::InstallData("pbmc3k")
# data("pbmc3k")
# 
# # Update the Seurat object
# pbmc3k <- UpdateSeuratObject(pbmc3k)
# 
# # Assign and check
# pbmc <- pbmc3k
# print(pbmc)
# 
# pbmc[["integrated"]] <- NULL
# pbmc@reductions$tsne <- NULL
# pbmc@reductions$umap <- NULL
# pbmc
# 
# SaveH5Seurat(pbmc, filename = "pbmc_example.h5Seurat")
# Convert("pbmc_example.h5Seurat", dest = "h5ad")

# write the files to gdrive

from google.colab import drive
drive.mount('/content/drive')

!cp pbmc_example.h5ad /content/drive/MyDrive/geneformer_test1/
!cp pbmc_example.h5Seurat /content/drive/MyDrive/geneformer_test1/

"""**convert data from Anndata to Loom via Anndata.write_loom**"""

import anndata
adata = anndata.read_h5ad("./pbmc_example.h5ad")

adata.obs

adata.var

adata.var_names

adata.var.index.values

"""*Load the gene book, and then compare it with our used genes to get the gene id*"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
file_path = '/content/gdrive/My Drive/geneformer_data/gene_info_table.csv'
genes = pd.read_csv(file_path)
print(genes.head())

gene_df = genes.drop(columns=["Unnamed: 0"])
print(gene_df.head())

"""**Matching the ENSEMBL ids with the Gene Symbols : code 1**"""

import pandas as pd
import numpy as np

# Load and clean the gene mapping file
genes = pd.read_csv(file_path)
print(genes.head())

gene_df = genes.drop(columns=["Unnamed: 0"])
print(gene_df.head())

# Step 1: Create a mapping dictionary from gene_name to ensembl_id
gene_to_ensembl = dict(zip(gene_df['gene_name'], gene_df['ensembl_id']))

# Step 2: Get current gene names from your AnnData
current_genes = adata.var.index.tolist()

# Step 3: Find which genes can be mapped
mappable_genes = []
ensembl_ids = []
gene_indices = []

for i, gene in enumerate(current_genes):
    if gene in gene_to_ensembl:
        mappable_genes.append(gene)
        # Remove version number if present (e.g., ENSG00000000003.15 -> ENSG00000000003)
        ensembl_id = gene_to_ensembl[gene].split('.')[0]
        ensembl_ids.append(ensembl_id)
        gene_indices.append(i)

print(f"Found {len(mappable_genes)} genes with Ensembl mappings out of {len(current_genes)} total genes")

# Step 4: Create filtered AnnData with only mappable genes
adata_filtered = adata[:, gene_indices]

# Step 5: Replace gene names with Ensembl IDs
adata_filtered.var.index = ensembl_ids

# Optional: Keep original gene names as a column for reference
adata_filtered.var['gene_name'] = mappable_genes

# Step 6: Add n_counts for Geneformer compatibility
adata_filtered.obs["n_counts"] = np.array(adata_filtered.X.sum(axis=1)).flatten()

print(f"Final AnnData: {adata_filtered.n_obs} cells × {adata_filtered.n_vars} genes")
print("Sample gene IDs:", adata_filtered.var.index[:5].tolist())

# Your AnnData now has Ensembl IDs as gene identifiers
adata_final = adata_filtered

# Write into loom format (next)
# adata_final.write_loom("pbms.option1.loom")
# print("Saved to: pbms.option1.loom")

# Verify Geneformer compatibility
print("\nGeneformer compatibility check:")
print(f"✓ Has n_counts: {'n_counts' in adata_final.obs.columns}")
print(f"✓ Gene format: {adata_final.var.index[0]} (Ensembl ID)")
print(f"✓ File saved as Loom format")

# List all available metadata columns
adata_final.obs.columns.tolist()
# Show the first 5 rows of cell metadata
adata_final.obs.head()

# List all available metadata columns
adata_final.var.columns.tolist()
# Show the first 5 rows of cell metadata
adata_final.var.head()

adata_final.obs["cell_type"] = adata.obs["seurat_annotations"]
adata_final.obs["organ_major"] = adata.obs["seurat_annotations"]
adata_final.obs["organ"] = adata.obs["seurat_annotations"]

# Display the first few rows and all columns of the observation metadata
print("Observation (Cell) Metadata (adata_final.obs.head()):")
print(adata_final.obs.head())

# Print all column names available in the observation metadata
print("\nColumns in Observation (Cell) Metadata:")
print(adata_final.obs.columns.tolist())

# You can also get a summary of a specific numerical column, e.g., 'n_counts'
# if 'n_counts' in adata_final.obs.columns:
#     print("\nSummary of 'n_counts' column:")
#     print(adata_final.obs['n_counts'].describe())

# Display the first few rows and all columns of the variable metadata
print("Variable (Gene) Metadata (adata_final.var.head()):")
print(adata_final.var.head())

# Print all column names available in the variable metadata
print("\nColumns in Variable (Gene) Metadata:")
print(adata_final.var.columns.tolist())

# Verify the gene identifiers (the index of adata_final.var)
print("\nGene Identifiers (adata_final.var.index[:5].tolist()):")
print(adata_final.var.index[:5].tolist())

# Check the total number of genes (variables)
print(f"\nTotal number of genes in adata_final: {adata_final.n_vars}")

from google.colab import drive
drive.mount('/content/drive')

# Write into loom format on gdrive
adata_final.write_loom("pbms.option1.loom")
print("Saved to: pbms.option1.loom")

# Define full path to your desired location in Google Drive
output_path = "/content/drive/My Drive/geneformer_test1/pbms.option1.loom"

# Save the AnnData object in Loom format
adata_final.write_loom(output_path)
print(f"Saved to: {output_path}")

# Verify Geneformer compatibility
print("\nGeneformer compatibility check:")
print(f"✓ Has n_counts: {'n_counts' in adata_final.obs.columns}")
print(f"✓ Gene format: {adata_final.var.index[0]} (Ensembl ID)")

adata_final.var_names

"""**Matching the ENSEMBL ids with the Gene Symbols : code 2**"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

file_path="/content/drive/My Drive/geneformer_test1/gene_info_table.csv"
genes = pd.read_csv(file_path)
print(genes.head())

gene_df = genes.drop(columns=["Unnamed: 0"])
print(gene_df.head())

# Create mapping and filter to only keep mappable genes
gene_to_ensembl = dict(zip(gene_df['gene_name'], gene_df['ensembl_id']))

# Find mappable genes
mappable_mask = adata.var.index.isin(gene_df['gene_name'])
adata_mapped = adata[:, mappable_mask]

# Get Ensembl IDs for the remaining genes
ensembl_ids = [gene_to_ensembl[gene].split('.')[0] for gene in adata_mapped.var.index]

# Update gene identifiers
adata_mapped.var.index = ensembl_ids
adata_mapped.var['ensembl_id'] = ensembl_ids

# Add required metadata for Geneformer
adata_mapped.obs['n_counts'] = np.array(adata_mapped.X.sum(axis=1)).flatten()

print(f"Final dataset ready for Geneformer: {adata_mapped.n_obs} cells × {adata_mapped.n_vars} genes")

# Save for Geneformer
adata_mapped.write_loom("pbms.option2.loom")
print("Saved to: pbms.option2.loom")

# Optional: Verification
print("\nGeneformer compatibility check:")
print(f"✓ Has n_counts: {'n_counts' in adata_mapped.obs.columns}")
print(f"✓ Gene format: {adata_mapped.var.index[0]} (should be ENSG...)")
print(f"✓ Data shape: {adata_mapped.shape}")

# Define full path to your desired location in Google Drive
output_path = "/content/drive/My Drive/geneformer_test1/pbms.option2.loom"

# Save the AnnData object in Loom format
adata_mapped.write_loom(output_path)
print(f"Saved to: {output_path}")

# Display the first few rows and all columns of the observation metadata
print("Observation (Cell) Metadata (adata_mapped.obs.head()):")
print(adata_mapped.obs.head())

# Print all column names available in the observation metadata
print("\nColumns in Observation (Cell) Metadata:")
print(adata_mapped.obs.columns.tolist())

# You can also get a summary of a specific numerical column, e.g., 'n_counts'
# if 'n_counts' in adata_mapped.obs.columns:
#     print("\nSummary of 'n_counts' column:")
#     print(adata_mapped.obs['n_counts'].describe())

# Display the first few rows and all columns of the variable metadata
print("Variable (Gene) Metadata (adata_mapped.var.head()):")
print(adata_mapped.var.head())

# Print all column names available in the variable metadata
print("\nColumns in Variable (Gene) Metadata:")
print(adata_mapped.var.columns.tolist())

# Verify the gene identifiers (the index of adata_mapped.var)
print("\nGene Identifiers (adata_mapped.var.index[:5].tolist()):")
print(adata_mapped.var.index[:5].tolist())

# Check the total number of genes (variables)
print(f"\nTotal number of genes in adata_mapped: {adata_mapped.n_vars}")

"""**Matching the ENSEMBL ids with the Gene Symbols : code 3**"""

import pandas as pd
import anndata as ad

genes = pd.read_csv(file_path)
print(genes.head())

gene_df = genes.drop(columns=["Unnamed: 0"])
print(gene_df.head())

# Step 1: Make sure gene_df is indexed by gene_name
gene_df = gene_df.set_index("gene_name")

# Step 2: Filter to genes that exist in gene_df
common_genes = [gene for gene in adata.var_names if gene in gene_df.index]

# Step 3: Get the corresponding Ensembl IDs
ensembl_ids = [gene_df.loc[gene, "ensembl_id"] for gene in common_genes]

# Step 4: Subset the AnnData object to only those genes
adata_cut = adata[:, [gene in common_genes for gene in adata.var_names]]

# Step 5: Replace gene names with Ensembl IDs
adata_cut.var_names = ensembl_ids

# Optional: Add ensembl_id as a column for clarity
adata_cut.var["ensembl_id"] = adata_cut.var_names

# Step 6: Add n_counts for Geneformer compatibility
adata_cut.obs["n_counts"] = np.array(adata_cut.X.sum(axis=1)).flatten()

# Optional: Also add n_genes (number of expressed genes per cell)
adata_cut.obs["n_genes"] = np.array((adata_cut.X > 0).sum(axis=1)).flatten()

# Verify the results
print(f"Final dataset: {adata_cut.n_obs} cells × {adata_cut.n_vars} genes")
print(f"Found {len(common_genes)} genes with Ensembl mappings")
print("n_counts summary:")
print(adata_cut.obs["n_counts"].describe())

import pandas as pd
import anndata as ad
import numpy as np

genes = pd.read_csv(file_path)
print(genes.head())

gene_df = genes.drop(columns=["Unnamed: 0"])
print(gene_df.head())

# Step 1: Make sure gene_df is indexed by gene_name
gene_df = gene_df.set_index("gene_name")

# Step 2: Filter to genes that exist in gene_df
common_genes = [gene for gene in adata.var_names if gene in gene_df.index]

# Step 3: Get the corresponding Ensembl IDs and CLEAN them
ensembl_ids = []
clean_common_genes = []

for gene in common_genes:
    ensembl_id = str(gene_df.loc[gene, "ensembl_id"]).split('.')[0]  # Convert to string and remove version

    # Only keep properly formatted Ensembl IDs
    if ensembl_id.startswith('ENSG') and len(ensembl_id) >= 15:
        ensembl_ids.append(ensembl_id)
        clean_common_genes.append(gene)
    else:
        print(f"Skipping malformed ID: {ensembl_id} for gene {gene}")

print(f"Kept {len(ensembl_ids)} genes with valid Ensembl IDs")

# Step 4: Subset the AnnData object to only those genes
adata_cut = adata[:, [gene in clean_common_genes for gene in adata.var_names]]

# Step 5: Replace gene names with clean Ensembl IDs
adata_cut.var_names = ensembl_ids

# Step 6: Clean the var DataFrame to ensure all columns are consistent
adata_cut.var = pd.DataFrame(index=adata_cut.var_names)
adata_cut.var["ensembl_id"] = adata_cut.var_names  # Add as string column

# Step 7: Add n_counts for Geneformer compatibility
adata_cut.obs["n_counts"] = np.array(adata_cut.X.sum(axis=1)).flatten()
adata_cut.obs["n_genes"] = np.array((adata_cut.X > 0).sum(axis=1)).flatten()

# Step 8: Ensure all data types are consistent
print("Data types check:")
print(adata_cut.var.dtypes)
print(adata_cut.obs.dtypes)

# Verify the results
print(f"Final dataset: {adata_cut.n_obs} cells × {adata_cut.n_vars} genes")
print(f"Sample Ensembl IDs: {adata_cut.var_names[:3].tolist()}")

# Save for Geneformer
try:
    adata_cut.write_loom("pbms.option3.loom")
    print("Saved to: pbms.option3.loom")
except Exception as e:
    print(f"Error saving: {e}")
    # Alternative: save as h5ad first to debug
    adata_cut.write_h5ad("pbms.option3.h5ad")
    print("Saved as h5ad for debugging")

# Display the first few rows and all columns of the observation metadata
print("Observation (Cell) Metadata (adata_cut.obs.head()):")
print(adata_cut.obs.head())

# Print all column names available in the observation metadata
print("\nColumns in Observation (Cell) Metadata:")
print(adata_cut.obs.columns.tolist())

# You can also get a summary of a specific numerical column, e.g., 'n_counts'
# if 'n_counts' in adata_cut.obs.columns:
#     print("\nSummary of 'n_counts' column:")
#     print(adata_cut.obs['n_counts'].describe())

# Display the first few rows and all columns of the variable metadata
print("Variable (Gene) Metadata (adata_cut.var.head()):")
print(adata_cut.var.head())

# Print all column names available in the variable metadata
print("\nColumns in Variable (Gene) Metadata:")
print(adata.var.columns.tolist()) # Using adata.var.columns to see original columns

# Verify the gene identifiers (the index of adata_cut.var)
print("\nGene Identifiers (adata_cut.var.index[:5].tolist()):")
print(adata_cut.var.index[:5].tolist())

# Check the total number of genes (variables)
print(f"\nTotal number of genes in adata_cut: {adata_cut.n_vars}")

# Define full path to your desired location in Google Drive
output_path = "/content/drive/My Drive/geneformer_test1/pbms.option3.loom"

# Save the AnnData object in Loom format
adata_cut.write_loom(output_path)
print(f"Saved to: {output_path}")

"""loom file structure:

├── matrix/          # Main expression data (genes × cells)

├── row_attrs/       # Gene metadata (gene names, IDs, etc.)

├── col_attrs/       # Cell metadata (cell types, conditions, etc.)

├── row_graphs/      # Optional: gene-gene relationships

├── col_graphs/      # Optional: cell-cell relationships

└── layers/          # Optional: additional data layers
"""

# Observation Metadata (Cells) 🔬
# The adata_final.obs DataFrame contains all the cell-specific annotations.
# You can inspect its structure and content using common Pandas methods.

# This output will show you columns like orig.ident, nCount_RNA, nFeature_RNA, percent.mt,
# and the n_counts and n_genes columns you added for Geneformer compatibility.

# Display the first few rows and all columns of the observation metadata
print("Observation (Cell) Metadata (adata_final.obs.head()):")
print(adata_final.obs.head())

# Print all column names available in the observation metadata
print("\nColumns in Observation (Cell) Metadata:")
print(adata_final.obs.columns.tolist())

# You can also get a summary of a specific numerical column, e.g., 'n_counts'
# if 'n_counts' in adata_final.obs.columns:
#     print("\nSummary of 'n_counts' column:")
#     print(adata_final.obs['n_counts'].describe())

# Variable Metadata (Genes) 🧬

# The adata_final.var DataFrame holds the gene-specific annotations.
# This is where you'd expect to see the Ensembl IDs as the primary identifiers (index)
# and potentially original gene symbols or other gene-related information as columns.

# Display the first few rows and all columns of the variable metadata
print("Variable (Gene) Metadata (adata_final.var.head()):")
print(adata_final.var.head())

# Print all column names available in the variable metadata
print("\nColumns in Variable (Gene) Metadata:")
print(adata_final.var.columns.tolist())

# Verify the gene identifiers (the index of adata_final.var)
print("\nGene Identifiers (adata_final.var.index[:5].tolist()):")
print(adata_final.var.index[:5].tolist())

# Check the total number of genes (variables)
print(f"\nTotal number of genes in adata_final: {adata_final.n_vars}")

# Add 'ensembl_id' as a new column to adata_final.var
# The values for this column will be taken directly from the current index of .var
adata_final.var['ensembl_id'] = adata_final.var.index.values

# Now, verify that the 'ensembl_id' column has been added
print("Variable (Gene) Metadata with 'ensembl_id' column (adata_final.var.head()):")
print(adata_final.var.head())

# Exclude the genes that contain the particle "unknown"

print("Original adata_final shape:", adata_final.shape)
print("Original adata_final.var.index[:5].tolist():", adata_final.var.index[:5].tolist())

# Create a boolean mask: True for IDs that DO NOT contain "unknown"
# We check the .var.index directly
genes_to_keep_mask = ~adata_final.var.index.str.contains("unknown", case=False, na=False)

# Filter the AnnData object using the mask
adata_filtered_unknown = adata_final[:, genes_to_keep_mask].copy()

print("\nFiltered adata_final shape (removed 'unknown' genes):", adata_filtered_unknown.shape)
print("Filtered adata_final.var.index[:5].tolist():", adata_filtered_unknown.var.index[:5].tolist())

# Optional: Verify that 'unknown' is no longer present in the index
# This might take a moment for very large datasets
# assert not any("unknown" in s for s in adata_filtered_unknown.var.index.tolist()), "Error: 'unknown' found in index after filtering!"
print("\nSuccessfully filtered out genes with 'unknown' in their Ensembl ID.")

adata_final = adata_filtered_unknown

# Verify the gene identifiers (the index of adata_final.var)
print("\nGene Identifiers (adata_final.var.index[:5].tolist()):")
print(adata_final.var.index[:5].tolist())

# Check the total number of genes (variables)
print(f"\nTotal number of genes in adata_final: {adata_final.n_vars}")

"""
**To use adata_final for the next steps**

Tokenizing .loom single cell RNA-seq data to rank value encoding .dataset format.

**Input data** is a directory with .loom files containing raw counts from single cell RNAseq data, including all genes detected in the transcriptome without feature selection.

**Genes** should be labeled with **Ensembl IDs (row attribute "ensembl_id")**, which provide a unique identifer for conversion to tokens. Other forms of gene annotations (e.g. gene names) can be converted to Ensembl IDs via Ensembl Biomart. Cells should be labeled with the total read count in the cell (column attribute "n_counts") to be used for normalization.

**No cell metadata** is required, but custom cell attributes may be passed onto the tokenized dataset by providing a dictionary of custom attributes to be added, which is formatted as loom_col_attr_name : desired_dataset_col_attr_name.

*For example, if the original .loom dataset has column attributes "cell_type" and "organ_major" and one would like to retain these attributes as labels in the tokenized dataset with the new names "cell_type" and "organ", respectively, the following custom attribute dictionary should be provided: {"cell_type": "cell_type", "organ_major": "organ"}.*

Additionally, if the original .loom file contains a cell column attribute called **"filter_pass",** this column will be used as a binary indicator of whether to include these cells in the tokenized data. All cells with "1" in this attribute will be tokenized, whereas the others will be excluded. One may use this column to indicate QC filtering or other criteria for selection for inclusion in the final tokenized dataset.

If one's data is in other formats besides .loom, one can use the relevant tools (such as Anndata tools) to convert the file to a .loom format prior to running the transcriptome tokenizer."""

import pandas as pd

print("=== VARIABLE (GENE) METADATA ===")
print(f"Number of genes: {adata_final.n_vars}")
print(f"Gene index name: {adata_final.var.index.name}")
print("\nVariable DataFrame:")
print(adata_final.var.head())
print(f"\nVariable columns: {list(adata_final.var.columns)}")
print(f"Variable dtypes:\n{adata_final.var.dtypes}")

print("\n" + "="*50)

print("=== OBSERVATION (CELL) METADATA ===")
print(f"Number of cells: {adata_final.n_obs}")
print(f"Cell index name: {adata_final.obs.index.name}")
print("\nObservation DataFrame:")
print(adata_final.obs.head())
print(f"\nObservation columns: {list(adata_final.obs.columns)}")
print(f"Observation dtypes:\n{adata_final.obs.dtypes}")

print("\n" + "="*50)

# Show the first few rows of gene metadata
print(adata_final.var.head())

# Show column names (fields) in gene metadata
print("Gene metadata columns:", adata_final.var.columns.tolist())

# Show the first few rows of cell metadata
print(adata_final.obs.head())

# Show column names (fields) in cell metadata
print("Cell metadata columns:", adata_final.obs.columns.tolist())

print(f"AnnData dimensions: {adata_final.n_obs} cells × {adata_final.n_vars} genes")

# For AnnData objects, use this syntax instead:

ds = adata_final
print(ds.shape)

# For AnnData, use .var and .obs instead of .ra and .ca
print("Variable (gene) metadata columns:", ds.var.columns.tolist())
print("Observation (cell) metadata columns:", ds.obs.columns.tolist())

# Show the actual metadata
print("\nGene metadata:")
print(ds.var.head())

print("\nCell metadata:")
print(ds.obs.head())

# Show expression data (first gene across all cells)
print("\nExpression data for first gene:")
print(ds.X[:, 0])

# If you want to use Loom syntax, you need to: Read the saved Loom file

import loompy

# Read the Loom file you created
with loompy.connect("/content/pbms.option1.loom") as ds:
    print(ds.shape)
    print("Row attributes (genes):", ds.ra.keys())
    print("Column attributes (cells):", ds.ca.keys())
    print("First gene expression:", ds[:, 0])

"""Key Differences:: AnnData <>  Loom

Description ::  adata.var <> ds.ra

Gene/row metadata :: adata.obs <> ds.ca

Cell/column metadata :: adata.X <> ds[:,:]

Expression :: matrixadata.var.columns <> ds.ra.keys()

"""