# -*- coding: utf-8 -*-
"""pancreas.Geneformer_train_test.v5.using.BertForSequenceClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eRNV8xwK2v4A7Ge1lXxdLNhZMTjdHLA

**Overall Purpose**

The code fine-tunes a pre-trained Geneformer model to classify pancreatic cell types from single-cell RNA-seq data that has been tokenized into gene sequences.

Key Sections:

**1. Setup & Environment**

Installs dependencies (scanpy, datasets, etc.)

Clones Geneformer repository

Sets up CUDA memory configuration

Mounts Google Drive for data access

**2. Data Loading & Exploration**

Loads tokenized pancreatic dataset

```
pancreas_dataset = "/content/drive/MyDrive/geneformer_test2/pancreas_scib.dataset"
token_dataset = load_from_disk(pancreas_dataset)
```

Data contains input_ids (tokenized genes), celltype, and other metadata

Explores cell type distribution with visualizations

**3. Data Preprocessing Pipeline**

Filter rare cell types (>10% threshold)

```
clusters_to_keep = [k for k, v in celltype_counter.items() if v > min_cells]

# Keep only full-length sequences (2048 tokens)
filtered_data = filtered_data.filter(lambda x: x["length"] == 2048, num_proc=16)

# Downsample to 1000 cells to avoid memory issues
target_total = 1000
```

**4. Memory Management**

Aggressive downsampling (1000 cells) to prevent CUDA OOM

Uses proportional sampling to maintain cell type ratios

Implements gradient checkpointing and other memory optimizations

**5. Label Preparation**

Create numerical labels for training

target_names = sorted(list(set(train_data["label"])))

celltype_label_dict = {name: idx for idx, name in enumerate(target_names)}

**6. Model Training**

Load pre-trained Geneformer

```
model = BertForSequenceClassification.from_pretrained(
    MODEL,
    num_labels=len(celltype_label_dict.keys()),
    output_attentions=False,
    output_hidden_states=False
).to("cuda")

```

**7. Training Configuration**

Uses conservative settings to avoid memory issues

Implements gradient accumulation and checkpointing

Includes comprehensive evaluation metrics

**Key Features:**

*Memory Optimization:*

Dataset downsampling (1000 cells)

Gradient checkpointing enabled

Batch size = 5 with gradient accumulation

Sequence length capped at 2048

*Data Quality:*

Filters rare cell types (>10% threshold)

Only uses full-length sequences

Maintains proportional cell type distribution

*Biological Relevance:*

Focuses on pancreatic islet cells (beta, alpha, delta, etc.)

Includes cell type distribution analysis

Provides biological context for each cell type

**Overall Purpose**

The code fine-tunes a pre-trained Geneformer model to classify pancreatic cell types from single-cell RNA-seq data that has been tokenized into gene sequences.

Key Sections:

**1. Setup & Environment**

Installs dependencies (scanpy, datasets, etc.)

Clones Geneformer repository

Sets up CUDA memory configuration

Mounts Google Drive for data access

**2. Data Loading & Exploration**

Loads tokenized pancreatic dataset

```
pancreas_dataset = "/content/drive/MyDrive/geneformer_test2/pancreas_scib.dataset"
token_dataset = load_from_disk(pancreas_dataset)
```

Data contains input_ids (tokenized genes), celltype, and other metadata

Explores cell type distribution with visualizations

**3. Data Preprocessing Pipeline**

Filter rare cell types (>10% threshold)

```
clusters_to_keep = [k for k, v in celltype_counter.items() if v > min_cells]

# Keep only full-length sequences (2048 tokens)
filtered_data = filtered_data.filter(lambda x: x["length"] == 2048, num_proc=16)

# Downsample to 1000 cells to avoid memory issues
target_total = 1000
```

**4. Memory Management**

Aggressive downsampling (1000 cells) to prevent CUDA OOM

Uses proportional sampling to maintain cell type ratios

Implements gradient checkpointing and other memory optimizations

**5. Label Preparation**

Create numerical labels for training

target_names = sorted(list(set(train_data["label"])))

celltype_label_dict = {name: idx for idx, name in enumerate(target_names)}

**6. Model Training**

Load pre-trained Geneformer

```
model = BertForSequenceClassification.from_pretrained(
    MODEL,
    num_labels=len(celltype_label_dict.keys()),
    output_attentions=False,
    output_hidden_states=False
).to("cuda")

```

**7. Training Configuration**

Uses conservative settings to avoid memory issues

Implements gradient accumulation and checkpointing

Includes comprehensive evaluation metrics

**Key Features:**

*Memory Optimization:*

Dataset downsampling (1000 cells)

Gradient checkpointing enabled

Batch size = 5 with gradient accumulation

Sequence length capped at 2048

*Data Quality:*

Filters rare cell types (>10% threshold)

Only uses full-length sequences

Maintains proportional cell type distribution

*Biological Relevance:*

Focuses on pancreatic islet cells (beta, alpha, delta, etc.)

Includes cell type distribution analysis

Provides biological context for each cell type

**Overall Purpose**

The code fine-tunes a pre-trained Geneformer model to classify pancreatic cell types from single-cell RNA-seq data that has been tokenized into gene sequences.

Key Sections:

**1. Setup & Environment**

Installs dependencies (scanpy, datasets, etc.)

Clones Geneformer repository

Sets up CUDA memory configuration

Mounts Google Drive for data access

**2. Data Loading & Exploration**

Loads tokenized pancreatic dataset

```
pancreas_dataset = "/content/drive/MyDrive/geneformer_test2/pancreas_scib.dataset"
token_dataset = load_from_disk(pancreas_dataset)
```

Data contains input_ids (tokenized genes), celltype, and other metadata

Explores cell type distribution with visualizations

**3. Data Preprocessing Pipeline**

Filter rare cell types (>10% threshold)

```
clusters_to_keep = [k for k, v in celltype_counter.items() if v > min_cells]

# Keep only full-length sequences (2048 tokens)
filtered_data = filtered_data.filter(lambda x: x["length"] == 2048, num_proc=16)

# Downsample to 1000 cells to avoid memory issues
target_total = 1000
```

**4. Memory Management**

Aggressive downsampling (1000 cells) to prevent CUDA OOM

Uses proportional sampling to maintain cell type ratios

Implements gradient checkpointing and other memory optimizations

**5. Label Preparation**

Create numerical labels for training

target_names = sorted(list(set(train_data["label"])))

celltype_label_dict = {name: idx for idx, name in enumerate(target_names)}

**6. Model Training**

Load pre-trained Geneformer

```
model = BertForSequenceClassification.from_pretrained(
    MODEL,
    num_labels=len(celltype_label_dict.keys()),
    output_attentions=False,
    output_hidden_states=False
).to("cuda")

```

**7. Training Configuration**

Uses conservative settings to avoid memory issues

Implements gradient accumulation and checkpointing

Includes comprehensive evaluation metrics

**Key Features:**

*Memory Optimization:*

Dataset downsampling (1000 cells)

Gradient checkpointing enabled

Batch size = 5 with gradient accumulation

Sequence length capped at 2048

*Data Quality:*

Filters rare cell types (>10% threshold)

Only uses full-length sequences

Maintains proportional cell type distribution

*Biological Relevance:*

Focuses on pancreatic islet cells (beta, alpha, delta, etc.)

Includes cell type distribution analysis

Provides biological context for each cell type
"""

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

!pip install scanpy
!pip install loompy
!pip install datasets

!git lfs install
!git clone https://huggingface.co/ctheodoris/Geneformer
!ls -1

# Commented out IPython magic to ensure Python compatibility.
# %cd Geneformer
!pip install -e .

# Mount Google Drive

from google.colab import drive
drive.mount('/content/drive')

"""**Load and check the input .dataset after tokenization**"""

# Copy from Google Drive

import loompy
import scanpy
import datasets
from datasets import load_from_disk

pancreas_dataset = "/content/drive/My Drive/geneformer_test2/pancreas_scib_V1model.dataset"
token_dataset = load_from_disk(pancreas_dataset)

# Print basic info
print("Type of loaded dataset:", type(token_dataset))
print("Dataset summary:")
print(token_dataset)

# Print the feature schema (columns and types)
print("Dataset features:")
print(token_dataset.features)

# Preview the first 2 records
print("\nFirst 2 records:")
print(token_dataset[:2])

# Convert to pandas DataFrame and display the first few rows
df = token_dataset.to_pandas()
print("\nHead of the dataset as pandas DataFrame:")
print(df.head())

# input_ids
# A list of integers, where each integer represents a tokenized gene (mapped from an Ensembl ID) using Geneformer's tokenizer.
# These are the input tokens for the transformer model (similar to word tokens in NLP).

original_dataset = token_dataset

"""**input_ids** - tokenized expression (int IDs representing Ensembl genes)

**cell metadata** - celltype, tech, n_counts, obs_names, batch, etc.

In a Geneformer .dataset object (loaded with load_from_disk()), you cannot directly see gene names — only the input_ids, which are integers (tokens) that represent genes.

These token IDs were created during tokenization by mapping Ensembl gene IDs to integers using a token dictionary. The gene names themselves are not stored inside the .dataset — but - you can recover gene names in the following way :

```
import pickle

with open("/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl", "rb") as f:
    token_dict = pickle.load(f)

# Reverse it: token ID → gene (usually Ensembl ID)
token_to_gene = {v: k for k, v in token_dict.items()}

```
"""

# Save the dataset to the new folder
token_dataset.save_to_disk("/content/pancreas_scib.dataset")
print(f"Dataset successfully saved to /content/pancreas_scib.dataset")

print(df["input_ids"].head())

!ls -1 /content/pancreas_scib.dataset

import os
import subprocess
os.environ["NCCL_DEBUG"] = "INFO"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = ""

def find_gpus(nums=1):
    if nums == 1:
        return ['0']

    os.system('nvidia-smi -q -d Memory | grep Free >tmp_free_gpus')
    with open('tmp_free_gpus', 'r') as lines_txt:
        frees = lines_txt.readlines()
        idx_freeMemory_pair = [ (idx,int(x.split()[2]))
                              for idx,x in enumerate(frees) ]

    idx_freeMemory_pair_correct = []
    step = int(len(idx_freeMemory_pair) / nums)
    for i in range(0, len(idx_freeMemory_pair), step):
        obj = idx_freeMemory_pair[i]
        obj = (int(obj[0]/step), obj[1])
        idx_freeMemory_pair_correct.append(obj)

    idx_freeMemory_pair_correct.sort(key=lambda my_tuple:my_tuple[1],reverse=True)
    usingGPUs = [str(idx_memory_pair[0])
                    for idx_memory_pair in idx_freeMemory_pair_correct[:nums] ]

    print('using GPU idx: #', usingGPUs)
    return usingGPUs

n_gpus = str(subprocess.check_output(["nvidia-smi", "-L"])).count('UUID')
os.environ['CUDA_VISIBLE_DEVICES'] = ','.join(find_gpus(nums=n_gpus)[0])

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import datetime
import glob
import pickle
import subprocess

import numpy as np
import pandas as pd
import seaborn as sns

from collections import Counter, defaultdict

from datasets import Dataset, DatasetDict, load_from_disk

from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split

from transformers import BertForSequenceClassification, Trainer
from transformers.training_args import TrainingArguments

from geneformer import Classifier, DataCollatorForCellClassification, EmbExtractor

"""***Set up environment variables***"""

import sys, os
LIB_PATH=sys.path[1].split("/lib/")[0]
LFS_HOME=f"{LIB_PATH}/bin/git-lfs"
print(LFS_HOME)
# os.system(f"{LFS_HOME} install")
# os.system(f"{LFS_HOME} clone https://huggingface.co/ctheodoris/Geneformer")
# os.system(f"cd ./Geneformer && {LFS_HOME} pull")

!pwd
!ls -1 ../

!echo -e "\nThe files in the folder : pancreas_scib.dataset\n"
!ls -1 /content/pancreas_scib.dataset

# Pre-train model directory

# pre_model_dir = glob.glob(os.path.join(repo_dir,"*-12L-30M*"))[0]   ### use 12-layer Geneformer model
# pre_model_dir = glob.glob(os.path.join(repo_dir, "*-6L-30M*"))[0]  ### use 6-layer Geneformer model

# Input data set path
# input_prefix = "pancreas_scib"

# pancreas_dataset = token_dataset
original_dataset = token_dataset

# Specific paths

token_dictionary = "/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl"
model_v1 = "/content/Geneformer/Geneformer-V1-10M/"
model_v2 = "/content/Geneformer/Geneformer-V2-104M"

input_dir = "/content/content/pancreas_scib.dataset"
output_dir = "/content/pancreas_scib.classification_output"
input_prefix = "pancreas_scib"

print("Loading pancreas dataset...")

# Load the main pancreas dataset
original_dataset = load_from_disk(f"/content/pancreas_scib.dataset/")

print(f"Total cells loaded: {len(original_dataset)}")
print(f"Dataset features: {original_dataset.features}")

# Check if celltype column exists
if "celltype" in original_dataset.features:
    print("✅ 'celltype' is present in the dataset.")
else:
    print("❌ 'celltype' is NOT present in the dataset.")
    print("Available columns:", list(original_dataset.features.keys()))

# ============================================================================
# DATA PREP
# ============================================================================

# Load and prepare dataset (pancreas dataset)
# original_dataset = load_from_disk(f"{input_dir}/pancreas_dataset.dataset")

# The train_test_split method from the 🤗 Hugging Face datasets library,
# which operates on a Dataset object (like original_dataset).

# x["train"] → 80%
# x["test"] → 20%

# An example :

# x = original_dataset.train_test_split(test_size=0.2, seed=42)
# train_data = x["train"]
# test_data = x["test"]

# Print summary
# print("Training set:")
# print(train_data)
# print("Number of samples:", len(train_data))

# print("\nTest set:")
# print(test_data)
# print("Number of samples:", len(test_data))

# from pprint import pprint

# Print the first 4 rows of the training set
# pprint(train_data[:4])

# Print the first 4 rows of the testing set
# pprint(test_data[:4])

# for i in range(4):
#    print({k: train_data[i][k] for k in ["celltype", "n_counts", "length"]})

# for i in range(4):
#    print({k: test_data[i][k] for k in ["celltype", "n_counts", "length"]})

# The length refers to the number of tokens (gene IDs) used to represent each cell after tokenization.
# This is what Geneformer uses as the input sequence length for each cell. It is capped (often at 2048) to fit the model's maximum input size.

# The Counter is used here to count the frequency of each cell type in your dataset. Let me explain why this is important:

import matplotlib.pyplot as plt

celltype_counter = Counter(original_dataset["celltype"])
print(f"\n📊 Cell type distribution (raw counts): {celltype_counter}")

plt.figure(figsize=(6, 4))
plt.bar(celltype_counter.keys(), celltype_counter.values())
plt.xlabel("Cell Type")
plt.ylabel("Count")
plt.title("Cell Type Distribution")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# 🔢 Calculate and print percentages
total = sum(celltype_counter.values())
percentages = {cell: f"{100 * count / total:.1f}%" for cell, count in celltype_counter.items()}
print("\n📈 Cell type percentages:")
for cell_type, pct in percentages.items():
    print(f"{cell_type}: {pct}")

"""**To Identify Rare Cell Types**

*clusters_to_keep = [k for k, v in celltype_counter.items() if v > len(train_data) * 0.005]*

and to filter out cell types that appear in less than 0.5% of your data, and  to prevent training problems.

**Class imbalance:** If you have 10,000 acinar cells but only 5 rare cells, the model will be biased.

**Insufficient samples:** Can't learn meaningful patterns from very few examples

**Poor generalization:** Model might overfit to rare classes.
"""

# Keep cell types that appear in more than 0.1 of training data

threshold = 0.1  # 10% expressed as a decimal
min_cells = len(original_dataset) * threshold

clusters_to_keep = [k for k, v in celltype_counter.items() if v > min_cells]
print(f"\n✅ Cell types to keep (>0.1% threshold = {int(min_cells)} cells): {len(clusters_to_keep)} types")
print(f"🧪 Retained cell types: {clusters_to_keep}")

# ℹ️ Quick breakdown of pancreatic islet cell types
print("""
🔬 Pancreatic islet cell functions:
- Beta (β): secrete insulin (lowers blood glucose)
- Alpha (α): secrete glucagon (raises blood glucose)
- Delta (δ): secrete somatostatin (inhibits insulin and glucagon)
- PP (γ/F): secrete pancreatic polypeptide
- Epsilon (ε): secrete ghrelin
""")

# 📊 Compute and display filtered cell type distribution
total_cells = sum(celltype_counter[k] for k in clusters_to_keep)

print("📈 Cell type distribution (filtered):")
for k in clusters_to_keep:
    count = celltype_counter[k]
    pct = 100 * count / total_cells
    print(f"{k}: {count} cells ({pct:.2f}%)")

# Step 1: Filter data to keep only frequent cell types
filtered_data = original_dataset.filter(lambda x: x["celltype"] in clusters_to_keep, num_proc=16)

# Step 2: Keep only cells with full-length tokenization
filtered_data = filtered_data.filter(lambda x: x["length"] == 2048, num_proc=16)

# Step 3: Add a new column 'label' that copies 'celltype'
filtered_data = filtered_data.map(lambda x: {"label": x["celltype"]})

# Step 4: Shuffle the dataset for unbiased splits
shuffled_data = filtered_data.shuffle(seed=42)

# Step 5: Inspect the DataFrame
df = shuffled_data.to_pandas()
print(df.head())
print(f"\n📊 Shape of shuffled dataset: {df.shape}")

# ✅ Now shuffled_data will contain both celltype and label columns.

# instead of Renaming (shuffle + rename_column) :
# shuffled_data = filtered_data.shuffle(seed=42).rename_column("celltype", "label")

# Why rename to "label"?
# Standard ML convention - most training frameworks expect a column called "label"
# HuggingFace compatibility - Trainer expects numerical labels in a "label" column
# Prepares for next step - where we'll convert text labels to numbers

# Why shuffle?
# Randomizes order of cells in the dataset
# Prevents bias during train/eval splits
# seed=42 ensures reproducible results

# Why do we shuffle a dataset?

# Avoid Ordering Bias
# Biological or technical datasets may have samples grouped by condition, timepoint, or batch.
# If we don't shuffle, training data might be biased (e.g., early batches all beta cells, later batches all alpha cells).

# Improve Generalization
# Helps models learn robust patterns by seeing more diverse examples early and throughout training.

# Ensure Balanced Batches
# Training in mini-batches benefits from a mix of classes or cell types.
# Shuffling helps maintain class balance across batches.

# Prevents Overfitting
# Learning from patterns in ordering (like repeated samples from the same donor) may cause overfitting.
# Shuffling breaks those patterns.

"""To downsize the data to 3000 cells, keeping the same % of cells, nin order not to get CUDA out of memory ("CUDA out of memory. Tried to allocate 1.56 GiB. GPU 0 has a total capacity of 39.56 GiB of which 404.88 MiB is free. Process 5476 has 39.15 GiB memory in use. Of the allocated memory 37.55 GiB is allocated by PyTorch, and 1.11 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management")  """

# The percentage of each cell type in the shuffled_data

from collections import Counter

# Count cell types
celltype_counter = Counter(shuffled_data["celltype"])

# Compute percentages
total_cells = sum(celltype_counter.values())
percentages = {cell: 100 * count / total_cells for cell, count in celltype_counter.items()}

# Print results
print(f"\n📊 Cell type distribution in shuffled dataset (total = {total_cells} cells):")
for cell_type, count in celltype_counter.items():
    pct = percentages[cell_type]
    print(f"{cell_type}: {count} cells ({pct:.2f}%)")

import matplotlib.pyplot as plt

# === Pie Chart Visualization ===
labels = [f"{cell} ({count}, {percentages[cell]:.1f}%)" for cell, count in celltype_counter.items()]
sizes = list(celltype_counter.values())

plt.figure(figsize=(5, 5))
plt.pie(sizes, labels=labels, startangle=140, wedgeprops={"edgecolor": "white"})
plt.title(f"📊 Cell Type Distribution (n = {total_cells} cells)", fontsize=10)
plt.axis("equal")  # Equal aspect ratio ensures the pie is round
plt.tight_layout()
plt.show()

target_total = 1000

"""**Down-sampling **

Total target cells

target_total = 1000
"""

# ✅ Next step: Create the downsampled dataset
from datasets import concatenate_datasets

# === Compute sample sizes based on existing proportions ===
sample_sizes = {
    k: int(round(v / total_cells * target_total)) for k, v in celltype_counter.items()
}

# Adjust to ensure total is exactly target_total (e.g., 2000)
diff = target_total - sum(sample_sizes.values())
if diff != 0:
    largest = max(sample_sizes, key=sample_sizes.get)
    sample_sizes[largest] += diff

# === Downsample each group ===
downsampled_groups = [
    shuffled_data.filter(lambda x: x["celltype"] == k).shuffle(seed=42).select(range(sample_sizes[k]))
    for k in sample_sizes
]

# === Combine downsampled groups ===
downsampled_dataset = concatenate_datasets(downsampled_groups)

# === Check final cell distribution ===
final_counts = Counter(downsampled_dataset["celltype"])
print(f"\n✅ Final downsampled dataset (n = {target_total}):")
for k, v in final_counts.items():
    print(f"{k}: {v} cells ({100 * v / target_total:.2f}%)")

print(f"🎯 Downsampled dataset contains {len(downsampled_dataset)} cells.")
print("📊 Distribution:")
from collections import Counter
from pprint import pprint

ct_counts = Counter(downsampled_dataset["celltype"])
pprint({k: f"{v} cells ({v / len(downsampled_dataset) * 100:.2f}%)" for k, v in ct_counts.items()})

# Now, downsampled_dataset is the actual object to use going forward — for example, for splitting into train/test:

# x = downsampled_dataset.train_test_split(test_size=0.2, seed=42)
# pancreas_trainset = x["train"]
# pancreas_evalset = x["test"]

train_data = downsampled_dataset

"""**Input training data : to create numerical labels**"""

# Create numerical labels from downsampled train_data
target_names = sorted(list(set(train_data["label"])))
celltype_label_dict = {name: idx for idx, name in enumerate(target_names)}
print(f"Label mapping: {celltype_label_dict}")

# Map string labels to numerical values
def map_labels(example):
    example["label"] = celltype_label_dict[example["label"]]
    return example

# Apply the mapping
labeled_data = train_data.map(map_labels, num_proc=16)

# Convert to pandas for inspection
import pandas as pd
df = labeled_data.to_pandas()
print(df.head())

from collections import Counter
import matplotlib.pyplot as plt

# Count number of cells per numeric label
cell_counts = Counter(labeled_data["label"])

# Sort by count
sorted_items = sorted(cell_counts.items(), key=lambda x: x[1], reverse=True)
labels, counts = zip(*sorted_items)

# Optionally map numeric labels back to cell type names for the x-axis
inverse_label_map = {v: k for k, v in celltype_label_dict.items()}
x_labels = [inverse_label_map[i] for i in labels]

# Plot
plt.figure(figsize=(4, 4))
plt.bar(x_labels, counts)
plt.xlabel("Cell Type")
plt.ylabel("Number of Cells")
plt.title("Cell Count per Cell Type (Downsampled & Relabeled)")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Count occurrences of each numeric label
label_counts = Counter(labeled_data["label"])
total = sum(label_counts.values())

# Reverse mapping: numeric label → cell type name
label_to_celltype = {v: k for k, v in celltype_label_dict.items()}

# Print percentages
print("\n📊 Percentage of each label class:")
for label, count in sorted(label_counts.items()):
    cell_type = label_to_celltype[label]
    pct = 100 * count / total
    print(f"{cell_type}: {pct:.2f}%")

# Train/eval split (80% train, 20% eval from the filtered data)
train_size = round(len(labeled_data) * 0.8)
pancreas_trainset = labeled_data.select(range(train_size))
pancreas_evalset = labeled_data.select(range(train_size, len(labeled_data)))

print(f"Training set size: {len(pancreas_trainset)}")
print(f"Evaluation set size: {len(pancreas_evalset)}")
print(f"Number of unique cell types: {len(celltype_label_dict)}")

print(f"{output_dir}")

# Load dataset from disk to verify
# Save datasets for later use
pancreas_trainset.save_to_disk(f"{output_dir}/pancreas_labeled_train.dataset")
pancreas_evalset.save_to_disk(f"{output_dir}/pancreas_labeled_eval.dataset")

for fname in os.listdir(output_dir):
    print(os.path.join(output_dir, fname))

# Show column names (metadata) for each dataset
print("📋 labeled_data columns:")
print(labeled_data.column_names)

print("\n📋 pancreas_trainset columns:")
print(pancreas_trainset.column_names)

print("\n📋 pancreas_evalset columns:")
print(pancreas_evalset.column_names)



# ============================================================================
# METRICS
# ============================================================================

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    # calculate accuracy and macro f1 using sklearn's function
    acc = accuracy_score(labels, preds)
    macro_f1 = f1_score(labels, preds, average='macro')
    return {
      'accuracy': acc,
      'macro_f1': macro_f1
    }

import torch
import gc

# Clear GPU cache
torch.cuda.empty_cache()
gc.collect()

# Check GPU memory
print(f"GPU memory allocated: {torch.cuda.memory_allocated() / 1024**3:.2f} GB")
print(f"GPU memory reserved: {torch.cuda.memory_reserved() / 1024**3:.2f} GB")

import torch
torch.cuda.empty_cache()
print(f"CUDA memory after empty_cache: {torch.cuda.memory_allocated() / (1024**3):.2f} GB")
# ... your model loading and training code

"""**🔧 Hyperparameters :**

**max_input_size = 2048**

Maximum number of tokens (genes) per cell input.

If a cell expresses more than 2048 genes, it will be truncated; if fewer, it may be padded.

**geneformer_batch_size = 5**

Number of examples (cells) processed in one forward/backward pass.

A small batch size reduces memory usage but may make training slower or noisier.

**max_lr = 5e-5**

Maximum learning rate (i.e., 0.00005).

Controls the step size during optimization. Too high can overshoot; too low may converge slowly.

**lr_schedule_fn = "linear"**

Learning rate schedule. "linear" means the learning rate will decay linearly from max_lr to 0 across training steps.

Helps the model stabilize after initial updates.

**warmup_steps = 500**

Number of steps over which the learning rate will increase linearly from 0 to max_lr.

Helps prevent sudden jumps at the beginning of training.

**epochs = 30**

Number of full passes through the training dataset.

More epochs mean more training time and potential overfitting if too high.

**optimizer = "adamw"**

Optimization algorithm. AdamW is a version of Adam that decouples weight decay from the gradient update.

Well-suited for transformer-based models.

**freeze_layers = 0**

Number of transformer layers to "freeze" (not update during training).

If set > 0, the first freeze_layers will be frozen; 0 means the full model is trainable

**🔍 What is TrainingArguments?**

TrainingArguments is a class provided by the Hugging Face transformers library. It defines all the parameters needed to train or evaluate a model using the Trainer API.

```
training_args = {
    "learning_rate": 5e-5,
    "do_train": True,
    "do_eval": True,
    "eval_strategy": "epoch",
    "save_strategy": "epoch",
    "logging_steps": 100,
    "group_by_length": True,
    "length_column_name": "length",
    "disable_tqdm": False,
    "lr_scheduler_type": "linear",
    "warmup_steps": 500,
    "weight_decay": 0.01,
    "per_device_train_batch_size": 8,
    "per_device_eval_batch_size": 8,
    "num_train_epochs": 3,
    "load_best_model_at_end": True,

```
"""

# Hyperparameters (adapted from the simple approach)

num_proc = 16  # Number of processes for parallelism

# Not to get CUDA out of memory :
# In your hyperparameters section, change:
geneformer_batch_size = 5  # Reduce from 5 to 1

# set logging steps
logging_steps = round(len(pancreas_trainset)/geneformer_batch_size/10)

max_input_size = 2048
# max_input_size = 1024

max_lr = 5e-5

lr_schedule_fn = "linear"
# lr_schedule_fn = "cosine"
# lr_schedule_fn = "polynomial"

# warmup_steps = 100
warmup_steps = 500

epochs = 30

optimizer = "adamw"
freeze_layers = 0

# define output directory path

current_date = datetime.datetime.now()
datestamp = f"{str(current_date.year)[-2:]}{current_date.month:02d}{current_date.day:02d}"
model_output_dir = f"/content/models/{datestamp}_geneformer_CellClassifier_pancreas_L{max_input_size}_B{geneformer_batch_size}_LR{max_lr}_LS{lr_schedule_fn}_WU{warmup_steps}_E{epochs}_O{optimizer}_F{freeze_layers}/"

# ensure not overwriting previously saved model
saved_model_test = os.path.join(model_output_dir, f"pytorch_model.bin")
if os.path.isfile(saved_model_test) == True:
    raise Exception("Model already saved to this directory.")

# make output directory
os.makedirs(model_output_dir, exist_ok=True)

# ============================================================================
# SIMPLE TRAINING
# ============================================================================

# In another notebook, I have found these parameters :
# training_args = {
#    "per_device_train_batch_size": cellformer_batch_size,
#    "per_device_eval_batch_size": cellformer_batch_size,
#    "num_train_epochs": 0.9,
#    "learning_rate": 0.00087,
#    "lr_scheduler_type": "polynomial",
#    "warmup_steps": 1812,
#    "weight_decay":0.02828,
#    "seed": 73,
    # add other training hyperparameters as needed
# }


# set training arguments
training_args = {
    "learning_rate": max_lr,
    "do_train": True,
    "do_eval": True,
    "eval_strategy": "epoch",
    "save_strategy": "epoch",
    "logging_steps": logging_steps,
    "group_by_length": True,
    "length_column_name": "length",
    "disable_tqdm": False,
    "lr_scheduler_type": lr_schedule_fn,
    "warmup_steps": warmup_steps,
    #"weight_decay": 0.001,
     "weight_decay": 0.1,

     "per_device_train_batch_size": geneformer_batch_size,
     "per_device_eval_batch_size": geneformer_batch_size,
    #"per_device_train_batch_size": 1,
    #"per_device_eval_batch_size": 1,
    "num_train_epochs": epochs,
    "load_best_model_at_end": True,
    "output_dir": model_output_dir,

    # 🔥 ADD THESE MEMORY-SAVING OPTIONS:
    "gradient_checkpointing": True,
    "dataloader_pin_memory": False,
    "gradient_accumulation_steps": 4,  # Accumulate gradients
}

training_args_init = TrainingArguments(**training_args)
print(training_args_init)

"""```
model = BertForSequenceClassification.from_pretrained(
    MODEL,
    num_labels = len(celltype_label_dict.keys()),
    output_attentions = True,
    output_hidden_states = True
).to("cuda")
```

**🔍 Explanation**

**BertForSequenceClassification.from_pretrained(...)**

This loads a pretrained BERT model (like Geneformer) and adapts it for sequence classification — i.e., predicting a label for an input sequence (e.g., a cell's gene expression).

📌 Arguments

**MODEL**

This is a string path or model name pointing to a pretrained model directory (e.g., "geneformer" or "/content/models/geneformer_pretrained").

The model's weights and configuration will be loaded from this source.

**num_labels = len(celltype_label_dict.keys())**

Specifies how many distinct cell types (classes) the model should classify.

The final classification layer (nn.Linear) will output this many logits.

**output_attentions = True**

If True, the model will return attention weights for each layer and head.

Useful for interpreting which genes influenced the prediction.

**output_hidden_states = True**

If True, the model will return all hidden states from each layer.

These can be used for downstream tasks, feature extraction, or visualization.

**.to("cuda")**

Moves the model to the GPU, so training and inference can happen faster.

If you're not using a GPU, change it to .to("cpu")
"""

# Check what columns you have
print("labeled_data columns:", labeled_data.column_names)
print("pancreas_trainset columns:", pancreas_trainset.column_names)
print("pancreas_evalset columns:", pancreas_evalset.column_names)

# Check sample data
print("\nSample from pancreas_trainset:")
print(pancreas_trainset[0])

# Check if you have celltype_label_dict
if 'celltype_label_dict' in locals():
    print("\ncelltype_label_dict:", celltype_label_dict)

# Check if you have celltype_label_dict
print("🔍 labeled_data features:")
print(labeled_data.features)

print("\n🔍 pancreas_trainset features:")
print(pancreas_trainset.features)

print("\n🔍 pancreas_evalset features:")
print(pancreas_evalset.features)

MODEL = model_v1

# ============================================================================
# TRAINING LOOP
# ============================================================================

print("Starting pancreas cell type classification...")

# We use: pancreas_trainset (already prepared above)
# We use: pancreas_evalset (already prepared above)
# We use: cell_type_label_dict (already prepared above)


# reload pretrained model
model = BertForSequenceClassification.from_pretrained(MODEL,
                                                      num_labels = len(celltype_label_dict.keys()),
                                                      output_attentions = False,
                                                      output_hidden_states = False).to("cuda")


# Freeze initial layers if specified
if freeze_layers > 0:
    for param in model.bert.embeddings.parameters():
        param.requires_grad = False
    for i in range(freeze_layers):
        for param in model.bert.encoder.layer[i].parameters():
            param.requires_grad = False


model.gradient_checkpointing_enable()

import torch
torch.cuda.empty_cache()

# Load token dictionary
with open(token_dictionary, "rb") as f:
    token_dict = pickle.load(f)

data_collator = DataCollatorForCellClassification(token_dictionary=token_dict)

# create the trainer
trainer = Trainer(
    model = model,
    args = training_args_init,
    data_collator = data_collator,
    train_dataset = pancreas_trainset,
    eval_dataset = pancreas_evalset,
    compute_metrics = compute_metrics # ← This is where you pass the function
)

# train the cell type classifier
trainer.train()

predictions = trainer.predict(pancreas_evalset)

with open(f"{model_output_dir}predictions.pickle", "wb") as fp:
    pickle.dump(predictions, fp)

trainer.save_metrics("eval", predictions.metrics)
trainer.save_model(model_output_dir)

print("✅ Training complete!")
print(f"Model saved to: {model_output_dir}")

# Get final results from training log (epoch 30)

print(trainer.state.log_history)
final_log = trainer.state.log_history[-2]  # -2 because last entry is usually training end
final_accuracy = final_log.get('eval_accuracy', 0.0)
final_f1 = final_log.get('eval_macro_f1', 0.0)

print(f"Final Results (Epoch 30):")
print(f"  Accuracy: {final_accuracy:.3f}")
print(f"  F1 Score: {final_f1:.3f}")

# Show training progression
print(f"\nTraining Progress:")
eval_logs = [log for log in trainer.state.log_history if 'eval_accuracy' in log]
if eval_logs:
    first_acc = eval_logs[0].get('eval_accuracy', 0.0)
    last_acc = eval_logs[-1].get('eval_accuracy', 0.0)
    print(f"  Epoch 1: {first_acc:.3f}")
    print(f"  Epoch {len(eval_logs)}: {last_acc:.3f}")

print(f"\nDataset: {len(pancreas_trainset)} train, {len(pancreas_evalset)} eval")
print(f"Cell types: {len(celltype_label_dict)}")

# 📦 Common metadata fields in Geneformer .dataset files include:

# Column Name	Description

# input_ids	    Tokenized gene expression values (used for model input)
# label	        The target class (numeric or string) for classification
# celltype	    Original cell type label (if not renamed)
# n_counts	    Number of RNA molecules per cell
# obs_names	    Unique cell/sample identifiers
# size_factors	Normalization factor for expression values
# tech	        Sequencing technology used (e.g., Smart-seq2, 10x Genomics)
# length	      Length of the input_ids vector (often 2048 for Geneformer)
# batch	        Batch ID, if included

print(original_dataset.features)
print(original_dataset.column_names)

# Load dataset from disk to verify
# pancreas_test_dataset = load_from_disk(f"{output_dir}/{input_prefix}_labeled_test.dataset")
# print(pancreas_test_dataset)
# pancreas_train_dataset = load_from_disk(f"{output_dir}/{input_prefix}_labeled_train.dataset")
# print(pancreas_train_dataset)

!ls -s /content/models/250717_geneformer_CellClassifier_pancreas_L2048_B5_LR5e-05_LSlinear_WU500_E30_Oadamw_F0

!echo -e "\ninput dataset\n"
!ls -1 /content/pancreas_scib.dataset
!echo -e "\noutput folder\n"
!ls -s /content/pancreas_scib.classification_output
!echo -e "\ntrain dataset\n"
!ls -s /content/pancreas_scib.classification_output/pancreas_labeled_train.dataset
!echo -e "\neval dataset\n"
!ls -s /content/pancreas_scib.classification_output/pancreas_labeled_eval.dataset

from datasets import load_from_disk
import pickle

# Should we be able to find the <cls> token

# Load dataset
dataset = load_from_disk("/content/drive/My Drive/geneformer_test2/pancreas_scib.dataset")

# Load the Geneformer token dictionary
with open("/content/Geneformer/geneformer/gene_dictionaries_30m/token_dictionary_gc30M.pkl", "rb") as f:
    token_dict = pickle.load(f)


print("Number of tokens:", len(token_dict))
print("Sample keys:", list(token_dict.keys())[:10])
for key in token_dict.keys():
    if str(key).lower() == "<cls>":
        print("Found <cls> as key:", key)